"""
Data schema models defining the state, telemetry, and execution schemas of the multi-agent system.
"""

from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field
from datetime import datetime, timezone
import uuid

# Represents an isolated, actionable unit of work generated by a planner agent
class PlanStep(BaseModel):
    step_id: str = Field(default_factory=lambda: str(uuid.uuid4()), description="Unique identifier for the plan step")
    title: str
    description: str
    dependencies: List[str] = []
    completed: bool = False
    
class ToolCall(BaseModel):
    tool_name: str
    arguments: Dict[str, Any]
    timestamp: datetime = Field(default_factory=datetime.now(timezone.utc))

class CodeArtifact(BaseModel):
    artifact_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    filename: str
    language: str = "python"
    content: str
    created_at: datetime = Field(default_factory=datetime.now(timezone.utc))

class ExecutionLog(BaseModel):
    timestamp: datetime = Field(default_factory=datetime.now(timezone.utc))
    level: str
    message: str

class ExecutionResult(BaseModel):
    success: bool
    stdout: Optional[str] = None
    stderr: Optional[str] = None
    exit_code: Optional[int] = None
    execution_time: Optional[float] = None

class AgentEvent(BaseModel):
    event_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    event_type: str
    source_agent: str
    timestamp: datetime = Field(default_factory=datetime.now(timezone.utc))
    payload: Dict[str, Any]

