import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({
  baseDirectory: dirname(fileURLToPath(import.meta.url)),
});

/**
 * docs/FRONTEND.md §2.1 and §12.1.
 *
 * Two rules are errors rather than warnings on purpose. `no-explicit-any` because a
 * generated contract that anything can opt out of with one `any` is not a contract
 * (§4.1); `exhaustive-deps` because the connect effect in `useRunStream` reads a cursor
 * and a filter from its closure, and a missing dependency there is a socket that
 * reconnects with a stale `after_seq` — a bug that only shows up on a flaky network.
 */
const config = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      "playwright-report/**",
      "test-results/**",
      // GENERATED. openapi-typescript's output is not written to our lint rules and
      // editing it to satisfy them would be edited away by the next regeneration.
      "src/lib/api.d.ts",
      // GENERATED by `next build`/`next dev`, for the same reason: it declares its
      // route types with a triple-slash reference, and Next rewrites the file on every
      // build regardless of what the linter thinks of it.
      "next-env.d.ts",
    ],
  },
  {
    rules: {
      "@typescript-eslint/no-explicit-any": "error",
      "react-hooks/exhaustive-deps": "error",
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      "no-restricted-globals": [
        "error",
        {
          name: "WebSocket",
          message:
            "Only src/hooks/useRunStream.ts may construct a WebSocket (docs/FRONTEND.md §3).",
        },
      ],
    },
  },
  {
    // The one exception to the rule above, stated where it is granted rather than
    // silently in an ignore list.
    files: ["src/hooks/useRunStream.ts", "tests/**"],
    rules: { "no-restricted-globals": "off" },
  },
];

export default config;
