"""The typed WebSocket contract stays total and stays exportable.

docs/FRONTEND.md §4.3: the frontend's discriminated `RunEvent` union is generated from
`PAYLOADS`, so a new `EventType` with no registry entry would silently generate a union
that is missing a member — and the store's "exhaustive" switch would compile with a hole
in it. That is the failure these tests exist to make loud.

The graph-topology fixture at the bottom is the other half of the same idea, from §13:
`frontend/src/lib/graphTopology.ts` is transcribed by hand from `engine/graph.py`, and a
node added to the graph would not otherwise fail a build anywhere.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest
from pydantic import BaseModel

from app.schemas.events import (
    CONTROL_EVENTS,
    PAYLOADS,
    TERMINAL_EVENTS,
    EventType,
)

REPO_ROOT = Path(__file__).resolve().parents[2]


def test_every_event_type_has_a_payload_model() -> None:
    missing = sorted(event.value for event in EventType if event not in PAYLOADS)
    assert not missing, (
        f"EventType members with no PAYLOADS entry: {missing}. "
        "Add a payload model in app/schemas/events.py and re-run `make gen-event-types`."
    )


def test_payload_registry_has_no_entries_outside_the_enum() -> None:
    assert set(PAYLOADS) <= set(EventType)


@pytest.mark.parametrize("event", sorted(EventType, key=lambda e: e.value))
def test_every_payload_model_is_json_schema_exportable(event: EventType) -> None:
    """The generator reads `model_json_schema()`; a model that cannot export breaks it."""
    model = PAYLOADS[event]
    assert issubclass(model, BaseModel)
    schema = model.model_json_schema(ref_template="#/$defs/{model}")
    assert schema["type"] == "object"


def test_control_and_terminal_sets_are_disjoint_and_within_the_enum() -> None:
    assert CONTROL_EVENTS <= set(EventType)
    assert TERMINAL_EVENTS <= set(EventType)
    assert not (CONTROL_EVENTS & TERMINAL_EVENTS)


def test_generated_event_schema_is_committed_and_current() -> None:
    """`make check-event-types` runs the same comparison; this catches it in `make test`."""
    import sys

    sys.path.insert(0, str(REPO_ROOT / "scripts"))
    import gen_event_types  # type: ignore[import-not-found]

    target = REPO_ROOT / "backend" / "app" / "schemas" / "events.schema.json"
    assert target.is_file(), "run `make gen-event-types`"
    assert target.read_text(encoding="utf-8") == gen_event_types.render_schema(), (
        "backend/app/schemas/events.schema.json has drifted — run `make gen-event-types`"
    )


def test_generated_schema_covers_every_event() -> None:
    target = REPO_ROOT / "backend" / "app" / "schemas" / "events.schema.json"
    document = json.loads(target.read_text(encoding="utf-8"))
    assert set(document["payloads"]) == {event.value for event in EventType}
    for name in document["payloads"].values():
        assert name in document["$defs"], f"{name} is referenced but not defined"


def test_graph_topology_fixture_matches_the_registered_nodes() -> None:
    """The fixture the frontend's topology test asserts against (§13).

    Written from the compiled graph rather than from a list kept next to it, so adding a
    node to `engine/graph.py` and forgetting the dashboard fails here first.
    """
    from app.engine.graph import build_graph

    graph = build_graph()
    registered = {
        name for name in graph.get_graph().nodes if name not in {"__start__", "__end__"}
    }

    fixture = REPO_ROOT / "frontend" / "tests" / "fixtures" / "graph-topology.json"
    assert fixture.is_file(), (
        "frontend/tests/fixtures/graph-topology.json is missing. It is generated by this "
        "test's sibling helper; write it with `make gen-graph-fixture`."
    )
    declared = set(json.loads(fixture.read_text(encoding="utf-8"))["nodes"])
    assert declared == registered, (
        "the frontend's graph topology fixture has drifted from engine/graph.py: "
        f"only in backend={sorted(registered - declared)}, "
        f"only in fixture={sorted(declared - registered)}"
    )
