/**
 * The hand-laid-out topology matches the compiled backend graph (§13).
 *
 * `graphTopology.ts` is transcribed by hand — it has to be, because layout coordinates
 * are a design decision, not a backend fact. Transcription is the sharp edge §4.5 names:
 * a node added to `engine/graph.py` would not otherwise fail a build anywhere in this
 * app, and the pane would quietly stop showing it.
 *
 * The fixture is generated by `make gen-graph-fixture` straight from `build_graph()`, and
 * a pytest case asserts the fixture itself is current. Between the two, adding a node
 * without touching the dashboard is two red builds rather than a silent omission.
 */

import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import {
  edgeKey,
  edgePath,
  GRAPH_EDGES,
  GRAPH_NODES,
  graphNode,
  VIEWBOX_HEIGHT,
  VIEWBOX_WIDTH,
} from "@/lib/graphTopology";

interface Fixture {
  nodes: string[];
  edges: { from: string; to: string }[];
}

// Resolved from the Vitest root rather than `import.meta.url`: under the jsdom
// environment the module URL is not a `file:` URL, and `fileURLToPath` refuses it.
const fixture = JSON.parse(
  readFileSync(join(process.cwd(), "tests/fixtures/graph-topology.json"), "utf8"),
) as Fixture;

/** `hitl_gate` is an `interrupt_before` marker, not a registered node (AGENTS.md §9). */
const real = GRAPH_NODES.filter((node) => !node.synthetic);

describe("graph topology", () => {
  it("declares exactly the nodes the backend registers", () => {
    expect([...real.map((node) => node.id)].sort()).toEqual([...fixture.nodes].sort());
  });

  it("declares exactly the edges the backend registers", () => {
    // Self-loops included: `researcher → researcher` is a registered conditional edge
    // (the bounded re-research round), not a drawing convenience.
    const declared = GRAPH_EDGES.map(edgeKey).sort();
    const registered = fixture.edges
      .map((edge) => `${edge.from}→${edge.to}`)
      .sort();
    expect(declared).toEqual(registered);
  });

  it("names only real nodes at both ends of every edge", () => {
    for (const edge of GRAPH_EDGES) {
      expect(graphNode(edge.from), `unknown source ${edge.from}`).toBeDefined();
      expect(graphNode(edge.to), `unknown target ${edge.to}`).toBeDefined();
    }
  });

  it("keeps every node inside the viewBox", () => {
    for (const node of GRAPH_NODES) {
      expect(node.x).toBeGreaterThan(0);
      expect(node.x).toBeLessThan(VIEWBOX_WIDTH);
      expect(node.y).toBeGreaterThan(0);
      expect(node.y).toBeLessThan(VIEWBOX_HEIGHT);
    }
  });

  it("does not stack two nodes on the same point", () => {
    const seen = new Set<string>();
    for (const node of GRAPH_NODES) {
      const point = `${node.x},${node.y}`;
      expect(seen.has(point), `${node.id} overlaps another node`).toBe(false);
      seen.add(point);
    }
  });

  it("produces a drawable path for every edge, including the self-loop", () => {
    for (const edge of GRAPH_EDGES) {
      const path = edgePath(edge);
      expect(path, `${edgeKey(edge)} has no path`).not.toBe("");
      expect(path.startsWith("M ")).toBe(true);
      expect(path).not.toContain("NaN");
    }
  });

  it("gives the researcher's self-loop an arc rather than a zero-length line", () => {
    const self = GRAPH_EDGES.find((edge) => edge.from === edge.to);
    expect(self).toBeDefined();
    expect(edgePath(self!)).toContain("C");
  });

  it("assigns every node a phase from the run's own vocabulary", () => {
    const phases = new Set([
      "INIT",
      "PLANNING",
      "RESEARCH",
      "IMPLEMENT",
      "EXECUTE",
      "DEBUG",
      "TRACK",
      "EVALUATE",
      "REPORT",
      "COMPLETE",
    ]);
    for (const node of GRAPH_NODES) expect(phases.has(node.phase)).toBe(true);
  });
});
