"""Baseline schema: tasks, agent_logs, artifacts.

Revision ID: 0001_baseline
Revises: None
Create Date: 2026-08-24 11:42:38.381170+00:00

This single revision replaces three near-duplicate "initial schema" revisions
(b9cff7b47159 -> 8e4ce31ef43e -> eb1aa4f709e4) of which the first two were empty
no-ops and only the third carried DDL (defect D-011). It was regenerated by
autogenerate against an empty database, so it reflects the ORM exactly.

If you have a database still stamped with one of the old revisions, tell Alembic
where it now stands instead of re-running the DDL:

    alembic stamp 0001_baseline

LangGraph's checkpoint tables are deliberately absent — AsyncPostgresSaver.setup()
owns them, and alembic/env.py filters them out of autogeneration (defect D-006).
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Named PostgreSQL types are created implicitly by CREATE TABLE but are never dropped
# implicitly, so downgrade has to remove this one by hand or the next upgrade fails
# with "type task_status_enum already exists".
task_status_enum = sa.Enum(
    'PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='task_status_enum'
)


# revision identifiers, used by Alembic.
revision: str = '0001_baseline'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Unique identifier for the task job.'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Concise descriptive title for the task.'),
    sa.Column('prompt', sa.Text(), nullable=False, comment='Original user prompt or query submitted to the platform.'),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='task_status_enum'), nullable=False, comment='Current execution state of the task.'),
    sa.Column('result', sa.JSON(), nullable=True, comment='Final JSON result payload returned by the multi-agent graph.'),
    sa.Column('error', sa.Text(), nullable=True, comment='Captured stack trace or error message if execution fails.'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the task was initially submitted.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the task record was last modified.'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_table('agent_logs',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Unique identifier for the log entry.'),
    sa.Column('task_id', sa.Uuid(), nullable=False, comment='Foreign key pointing to the associated Task.'),
    sa.Column('agent_name', sa.String(length=100), nullable=False, comment='Name of the agent emitting the log (e.g. planner, coder, debugger).'),
    sa.Column('level', sa.String(length=20), nullable=False, comment='Log severity level (INFO, WARNING, ERROR, DEBUG).'),
    sa.Column('message', sa.Text(), nullable=False, comment='Detailed log message emitted during node execution.'),
    sa.Column('metadata_json', sa.JSON(), nullable=True, comment='Structured JSON payload containing agent state or tool inputs/outputs.'),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False, comment='Exact UTC timestamp when the log entry was generated.'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_logs_agent_name'), 'agent_logs', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_logs_task_id'), 'agent_logs', ['task_id'], unique=False)
    op.create_index(op.f('ix_agent_logs_timestamp'), 'agent_logs', ['timestamp'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Unique identifier for the artifact.'),
    sa.Column('task_id', sa.Uuid(), nullable=False, comment='Foreign key referencing the owning Task.'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Artifact filename or resource identifier (e.g., train_model.py).'),
    sa.Column('artifact_type', sa.String(length=50), nullable=False, comment='Type category of artifact (code, model, report, dataset).'),
    sa.Column('file_path', sa.Text(), nullable=True, comment='Path to stored artifact file on disk or sandbox volume.'),
    sa.Column('content', sa.Text(), nullable=True, comment='Raw text or source code representation of the artifact.'),
    sa.Column('metadata_json', sa.JSON(), nullable=True, comment='Additional technical attributes (e.g. model metrics, file size).'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='UTC creation timestamp.'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_artifact_type'), 'artifacts', ['artifact_type'], unique=False)
    op.create_index(op.f('ix_artifacts_task_id'), 'artifacts', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artifacts_task_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_artifact_type'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_agent_logs_timestamp'), table_name='agent_logs')
    op.drop_index(op.f('ix_agent_logs_task_id'), table_name='agent_logs')
    op.drop_index(op.f('ix_agent_logs_agent_name'), table_name='agent_logs')
    op.drop_table('agent_logs')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
    task_status_enum.drop(op.get_bind(), checkfirst=True)
