"""Traceback parsing and error fingerprinting (ARCHITECTURE.md §7.3.3, AGENTS.md §7.4).

`sandbox_exec` turns stderr into a structured `ErrorRecord` with regexes over the standard
traceback format — **never with an LLM**. Routing that depends on a model's reading of
stderr is routing that fails nondeterministically, which principle P1 exists to prevent.

The fingerprint is the load-bearing part. It is deterministic and independent of where in
the traceback the failure happened, so `ValueError: could not convert string to float:
'male'` and the same error on `'female'` collapse to one identity. That is what lets the
Debugger recognise "this is the third failure of the same kind, the approach is wrong"
rather than seeing three unrelated errors, and what lets episodic memory retrieve the fix
that worked last time.
"""

from __future__ import annotations

import re

from app.engine.state import DatasetBinding, ErrorKind, ErrorRecord, SandboxOutcome

# `  File "/workspace/main.py", line 42, in <module>`
_FRAME = re.compile(r'^\s*File "(?P<file>[^"]+)", line (?P<line>\d+), in (?P<func>.+)$')
# The final `ExceptionType: message` line of a traceback.
_EXCEPTION = re.compile(r"^(?P<type>[A-Za-z_][A-Za-z0-9_.]*)\s*:\s*(?P<message>.*)$")

_QUOTED = re.compile(r"""(['"])(?:\\.|(?!\1).)*\1""")
_HEX = re.compile(r"0x[0-9a-fA-F]+")
_PATHS = re.compile(r"(/[\w.\-/]+)+")
_NUMBERS = re.compile(r"\b\d+\b")
_NON_SLUG = re.compile(r"[^a-z0-9]+")

# Exception type → ErrorKind. Ordinary dispatch, no cleverness: the mapping is a policy
# decision and belongs somewhere a human can read and edit it.
_KIND_BY_TYPE: dict[str, ErrorKind] = {
    "SyntaxError": ErrorKind.SYNTAX,
    "IndentationError": ErrorKind.SYNTAX,
    "TabError": ErrorKind.SYNTAX,
    "ModuleNotFoundError": ErrorKind.IMPORT,
    "ImportError": ErrorKind.IMPORT,
    "NameError": ErrorKind.NAME,
    "UnboundLocalError": ErrorKind.NAME,
    "TypeError": ErrorKind.TYPE,
    "AttributeError": ErrorKind.TYPE,
    "KeyError": ErrorKind.DATA,
    "IndexError": ErrorKind.SHAPE,
    "FileNotFoundError": ErrorKind.DATA,
    "IsADirectoryError": ErrorKind.DATA,
    "PermissionError": ErrorKind.DATA,
    "EmptyDataError": ErrorKind.DATA,
    "AssertionError": ErrorKind.ASSERTION,
    "MemoryError": ErrorKind.OOM,
    "TimeoutError": ErrorKind.TIMEOUT,
    "ValueError": ErrorKind.VALUE,
    "ArithmeticError": ErrorKind.RUNTIME,
    "ZeroDivisionError": ErrorKind.RUNTIME,
    "RuntimeError": ErrorKind.RUNTIME,
}

# A ValueError mentioning any of these is a dimension mismatch, which is a different bug
# with a different fix from an ordinary bad value — and the most common ML failure there is.
_SHAPE_HINTS = (
    "shape",
    "dimension",
    "broadcast",
    "size mismatch",
    "n_features",
    "axis",
)

# Deterministic, error-kind-specific guidance for the Debugger (AGENTS.md §6.1). Written
# here rather than generated by a model because the environment's constraints are facts.
ERROR_KIND_HINTS: dict[ErrorKind, str] = {
    ErrorKind.TIMEOUT: (
        "Execution exceeded the wall-clock limit. Reduce the search space, n_estimators, "
        "epochs, or CV folds. Prefer RandomizedSearchCV over GridSearchCV."
    ),
    ErrorKind.OOM: (
        "The container was killed for exceeding its memory limit. Reduce batch size, use "
        "dtype=float32, load with pd.read_parquet(columns=…), or process in chunks."
    ),
    ErrorKind.IMPORT: (
        "The module is not installed and cannot be installed — the sandbox has no network. "
        "Use only the allowlisted libraries."
    ),
    ErrorKind.DATA: (
        "The sandbox has no network. Datasets must come from /datasets per manifest.json. "
        "Check the exact path and column names of the bound dataset."
    ),
    ErrorKind.SHAPE: (
        "Shape mismatch. Print the .shape of every array before the failing operation and "
        "reconcile them."
    ),
    ErrorKind.CONTRACT_VIOLATION: (
        "The program exited 0 but /artifacts/metrics.json was missing or invalid. Every "
        "train step MUST write it, and every metric named in the criteria must be present."
    ),
    ErrorKind.VALIDATION_REJECTED: (
        "Static validation rejected the code before execution. Fix the listed rejections "
        "first — no container was launched."
    ),
}


def normalize_message(message: str) -> str:
    """Strip the incidental detail that makes two identical bugs look different."""
    text = _QUOTED.sub("", message)
    text = _HEX.sub("", text)
    text = _PATHS.sub("", text)
    text = _NUMBERS.sub("", text)
    return text.strip().lower()


def slugify(text: str) -> str:
    return _NON_SLUG.sub("-", text).strip("-")[:80]


def fingerprint(exception_type: str, message: str) -> str:
    """`{ExceptionType}:{slug-of-normalised-message}` — position independent.

    When normalisation empties the message the quoted literal *was* the message —
    `KeyError: 'target'` is the canonical case — and collapsing every KeyError in the
    system to one identity would be useless. There the literal is kept unquoted, so a
    missing `target` column stays distinguishable from a missing `diagnosis` one.
    """
    slug = slugify(normalize_message(message))
    if not slug:
        slug = slugify(_QUOTED.sub(lambda m: m.group(0)[1:-1], message).lower())
    return f"{exception_type or 'Unknown'}:{slug or 'no-message'}"


def classify_exception(exception_type: str, message: str) -> ErrorKind:
    kind = _KIND_BY_TYPE.get(exception_type, ErrorKind.RUNTIME)
    if kind is ErrorKind.VALUE and any(
        hint in message.lower() for hint in _SHAPE_HINTS
    ):
        return ErrorKind.SHAPE
    return kind


def parse_traceback(stderr: str) -> tuple[str, str, str | None, int | None]:
    """Extract `(exception_type, message, file, line)` from a Python traceback.

    The reported frame is the last one in `main.py`: a failure inside pandas is almost
    always caused by the line of generated code that called pandas, and that is the line
    the fix has to change.
    """
    lines = [line for line in (stderr or "").splitlines() if line.strip()]
    if not lines:
        return "", "", None, None

    exception_type = ""
    message = ""
    for line in reversed(lines):
        if line.startswith((" ", "\t")):
            continue
        match = _EXCEPTION.match(line.strip())
        if match and not match.group("type").startswith(("File", "Traceback")):
            exception_type = match.group("type").rsplit(".", 1)[-1]
            message = match.group("message").strip()
            break
    else:
        # No `Type: message` line at all — a bare exception name, or not a traceback.
        message = lines[-1].strip()

    file_name: str | None = None
    line_number: int | None = None
    for line in lines:
        frame = _FRAME.match(line)
        if frame and frame.group("file").endswith("main.py"):
            file_name = frame.group("file")
            line_number = int(frame.group("line"))

    return exception_type, message, file_name, line_number


def source_region(source: str, line_number: int | None, context: int = 5) -> str | None:
    """The ±`context` lines around the failure, numbered, for the Debugger prompt."""
    if not line_number or not source:
        return None
    lines = source.splitlines()
    if not 1 <= line_number <= len(lines):
        return None
    start = max(0, line_number - context - 1)
    end = min(len(lines), line_number + context)
    width = len(str(end))
    return "\n".join(
        f"{index + 1:>{width}} {'>' if index + 1 == line_number else ' '} {lines[index]}"
        for index in range(start, end)
    )


def error_from_traceback(
    stderr: str,
    *,
    revision: int,
    source: str | None = None,
) -> ErrorRecord:
    """Build the `ErrorRecord` for a crashed program."""
    exception_type, message, file_name, line_number = parse_traceback(stderr)
    kind = classify_exception(exception_type, message)
    return ErrorRecord(
        kind=kind,
        fingerprint=fingerprint(exception_type, message),
        exception_type=exception_type,
        message=message or "the program failed without a recognisable traceback",
        traceback=stderr or "",
        file=file_name,
        line=line_number,
        offending_source=source_region(source or "", line_number),
        revision=revision,
    )


def synthetic_error(
    kind: ErrorKind,
    message: str,
    *,
    revision: int,
    traceback_text: str = "",
) -> ErrorRecord:
    """An `ErrorRecord` for a failure with no traceback: timeout, OOM, contract, gate."""
    return ErrorRecord(
        kind=kind,
        fingerprint=fingerprint(kind.value, message),
        exception_type=kind.value,
        message=message,
        traceback=traceback_text,
        revision=revision,
    )


# `ModuleNotFoundError: No module named 'requests'` — the one detail that makes the
# IMPORT hint actionable rather than generic.
_MODULE_NAME = re.compile(r"No module named ['\"]([^'\"]+)['\"]")

# A rejection line the static gate produces for unparseable source. Reported as
# `ErrorKind.SYNTAX` rather than `VALIDATION_REJECTED` so the Debugger gets the hint for
# the bug it actually has: `ast.parse` failing is a typo, not a policy violation.
_SYNTAX_REJECTION = re.compile(r"\b(SyntaxError|IndentationError|TabError)\b")


def error_kind_hint(
    error: ErrorRecord,
    *,
    outcome: SandboxOutcome | None = None,
    dataset: DatasetBinding | None = None,
) -> str:
    """The environment-specific guidance for `error.kind` (AGENTS.md §6.1).

    Deterministic, and deliberately so. Every fact in it — the wall clock the profile
    allows, the peak RSS the container reached, the modules that exist in the image, the
    dataset the plan bound — is something the platform knows and a 7B model would
    otherwise guess at. Guessing produces the single most expensive failure in the debug
    loop: a diagnosis that proposes `pip install`, which cannot work and burns an
    iteration proving it.
    """
    base = ERROR_KIND_HINTS.get(error.kind, "")
    detail: list[str] = []

    if error.kind is ErrorKind.TIMEOUT and outcome is not None:
        limit = _profile_timeout(outcome.profile)
        detail.append(
            f"The `{outcome.profile}` profile allows {limit}s; this attempt was killed "
            f"after {outcome.duration_ms / 1000:.0f}s."
        )
    elif error.kind is ErrorKind.OOM and outcome is not None:
        if outcome.max_rss_bytes:
            detail.append(
                f"Peak resident memory was {outcome.max_rss_bytes / (1024 * 1024):.0f} MiB."
            )
    elif error.kind is ErrorKind.IMPORT:
        module = _MODULE_NAME.search(error.message)
        if module is not None:
            detail.append(f"The missing module is `{module.group(1)}`.")
        detail.append(f"Allowed modules: {_allowlist_text()}.")
    elif error.kind is ErrorKind.DATA and dataset is not None:
        target = (
            f", whose target column is `{dataset.target_column}`"
            if dataset.target_column
            else ""
        )
        detail.append(
            f"The dataset bound to this step is `{dataset.dataset_id}` at "
            f"`{dataset.path}`{target}."
        )
    elif error.kind is ErrorKind.CONTRACT_VIOLATION:
        detail.append(
            "metrics.json was never written."
            if "not written" in error.message
            else "metrics.json was written but did not satisfy the contract."
        )
    elif error.kind is ErrorKind.VALIDATION_REJECTED and outcome is not None:
        if outcome.validation.rejections:
            detail.append(
                "Rejections: " + "; ".join(outcome.validation.rejections) + "."
            )

    hint = " ".join(part for part in (base, *detail) if part).strip()
    return hint or "No environment-specific hint applies to this failure."


def consecutive_repeats(errors: list[ErrorRecord] | None) -> int:
    """How many of the most recent errors share the newest fingerprint.

    The anti-thrash signal (AGENTS.md §5.5 rule 4). A Coder–Debugger pair that keeps
    producing cosmetically different code failing in exactly the same way is the most
    common way an autonomous loop burns its whole budget, and this counter is the only
    evidence that distinguishes it from ordinary progress.
    """
    history = list(errors or [])
    if not history:
        return 0
    newest = history[-1].fingerprint
    count = 0
    for record in reversed(history):
        if record.fingerprint != newest:
            break
        count += 1
    return count


def validation_error(rejections: list[str], *, revision: int) -> ErrorRecord:
    """The `ErrorRecord` for code the static gate refused to launch.

    A rejection naming a `SyntaxError` is reported as `ErrorKind.SYNTAX`: the code does
    not parse, which is a different bug from an import the sandbox forbids, and the
    Debugger reasons better when the two are not conflated.
    """
    message = "; ".join(rejections) or "static validation refused the program"
    kind = (
        ErrorKind.SYNTAX
        if any(_SYNTAX_REJECTION.search(reason) for reason in rejections)
        else ErrorKind.VALIDATION_REJECTED
    )
    return synthetic_error(kind, message, revision=revision)


def _profile_timeout(profile: str) -> int:
    """The wall clock the named sandbox profile allows."""
    from app.services.sandbox import profile_for

    try:
        return profile_for(profile).timeout_s
    except ValueError:  # pragma: no cover - profile comes from a validated Literal
        return 0


def _allowlist_text() -> str:
    from app.services.validator import load_allowlist

    return ", ".join(sorted(load_allowlist()))
