import operator
from typing import Annotated, Any, Optional, TypedDict

from langchain_core.messages import BaseMessage


class AgentState(TypedDict):
    """Central state representation passed across all LangGraph agent nodes.

    Maintains workflow context, research materials, generated code, execution logs,
    and evaluation metrics throughout the multi-agent execution cycle.
    """

    task_id: str
    prompt: str

    # Message history with reducer annotation to combine incoming messages
    messages: Annotated[list[BaseMessage], operator.add]

    # Planning breakdown generated by the Planner Agent
    plan: list[str]
    current_step_index: int

    # RAG context collected by the Research Agent
    research_context: list[str]

    # Source code emitted by the Coding Agent
    code: str

    # Console stdout/stderr emitted by sandbox execution
    execution_output: str

    # Stack trace or error feedback captured by Debug Agent
    error: Optional[str]

    # Iteration tracking to avoid infinite self-correction loops
    iteration_count: int
    max_iterations: int

    # MLOps tracking details
    mlflow_run_id: Optional[str]
    eval_score: Optional[float]

    # Status tracking for current state node
    status: str
    metadata: dict[str, Any]