#!/usr/bin/env python3
"""Export the compiled graph's topology as a test fixture.

docs/FRONTEND.md §4.5 and §13: `frontend/src/lib/graphTopology.ts` is transcribed by hand
from `AGENTS.md` §4.1 — it has to be, because the live graph is a fixed-layout SVG and
layout coordinates are a design decision, not a backend fact. Transcription is the sharp
edge: a node added to `engine/graph.py` will not fail a build in the frontend.

This closes that edge with data rather than vigilance. The fixture is the *backend's* node
and edge set; a Vitest case asserts the hand-laid-out table covers exactly it, and a
pytest case asserts the fixture itself is current. Adding a node without touching the
dashboard is then two red builds, not a pane that quietly stops showing a node.

`make gen-graph-fixture` writes it; `--check` fails when it has drifted.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "backend"))

from app.engine.graph import build_graph  # noqa: E402

TARGET = REPO_ROOT / "frontend" / "tests" / "fixtures" / "graph-topology.json"

#: LangGraph's own sentinels. They are edges of the runtime, not nodes of the agent graph,
#: and the dashboard draws neither.
SENTINELS = {"__start__", "__end__"}


def render() -> str:
    graph = build_graph().get_graph()

    nodes = sorted(name for name in graph.nodes if name not in SENTINELS)
    edges = sorted(
        {
            (edge.source, edge.target)
            for edge in graph.edges
            if edge.source not in SENTINELS and edge.target not in SENTINELS
        }
    )

    document = {
        "$comment": (
            "GENERATED by scripts/gen_graph_fixture.py from backend/app/engine/graph.py. "
            "Asserted against frontend/src/lib/graphTopology.ts by both test suites."
        ),
        "nodes": nodes,
        "edges": [{"from": source, "to": target} for source, target in edges],
    }
    return json.dumps(document, indent=2, sort_keys=False) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if the fixture is stale.")
    args = parser.parse_args()

    generated = render()
    if args.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.is_file() else ""
        if current != generated:
            print(
                f"{TARGET.relative_to(REPO_ROOT)} is stale — run `make gen-graph-fixture`",
                file=sys.stderr,
            )
            return 1
        print(f"{TARGET.relative_to(REPO_ROOT)} is up to date.")
        return 0

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(generated, encoding="utf-8")
    print(f"Wrote {TARGET.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
