/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/benchmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List benchmark suites
         * @description Every suite in `benchmarks/suites/`, with its cases and their expectations.
         */
        get: operations["list_benchmark_suites_api_v1_benchmarks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/benchmarks/{suite}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Historical benchmark scores
         * @description Recorded results for a suite, newest first, with §13.1's KPIs computed over them.
         */
        get: operations["get_benchmark_results_api_v1_benchmarks__suite__results_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/benchmarks/{suite}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute a benchmark suite
         * @description Start a suite in the background and return the cases that will run.
         *
         *     The suite is loaded and the requested case ids validated *before* the 202, so a typo in
         *     a case name is an error the caller sees rather than a background task that quietly runs
         *     nothing.
         */
        post: operations["run_benchmark_suite_api_v1_benchmarks__suite__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corpus/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List corpus documents */
        get: operations["list_documents_api_v1_corpus_documents_get"];
        put?: never;
        /**
         * Ingest a corpus document
         * @description Chunk, embed and index a document into `rd_corpus` or `code_exemplars`.
         */
        post: operations["create_document_api_v1_corpus_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corpus/documents/{doc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a corpus document
         * @description Delete a document and every Qdrant point it was chunked into.
         */
        delete: operations["remove_document_api_v1_corpus_documents__doc_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corpus/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inspect retrieval directly
         * @description Run the same retrieval the Researcher uses, without a graph run — for debugging
         *     what a query actually surfaces before trusting it inside a prompt.
         */
        post: operations["search_corpus_api_v1_corpus_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Shallow Health Check
         * @description Returns basic service availability without pinging downstream dependencies.
         */
        get: operations["health_check_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/deep": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Deep Dependency Health Check
         * @description Pings PostgreSQL, Redis, Qdrant, MLflow, and Ollama concurrently.
         *
         *     Returns 503 when a hard dependency is down, 200 otherwise — `degraded` if a soft
         *     dependency (MLflow, Ollama) is unreachable.
         */
        get: operations["deep_health_check_api_v1_health_deep_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run detail */
        get: operations["get_run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Release a human-approval gate
         * @description Deliver a HITL decision to the worker waiting on the gate (§9.5's `approve`).
         *
         *     The gate itself is not built yet — §21 marks it outstanding — so today this delivers
         *     the signal and reports whether anything was listening. That is the honest behaviour
         *     for a half-built feature: the transport is real and testable, and an operator gets
         *     told plainly when no worker is waiting rather than a 202 that means nothing.
         */
        post: operations["approve_run_api_v1_runs__run_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a run
         * @description Signal a cooperative cancel (§9.5's `cancel`, §5.3's `RUNNING → CANCELLED`).
         */
        post: operations["cancel_run_api_v1_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Event backlog
         * @description The retained event log, read from the same stream the WebSocket replays.
         */
        get: operations["get_run_events_api_v1_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume from the last checkpoint
         * @description Re-enqueue an interrupted run (§5.3).
         *
         *     Refuses while the lock is held even if the row says `INTERRUPTED`: the reaper and a
         *     slow worker can disagree for one tick, and the lock is the more current of the two.
         */
        post: operations["resume_run_endpoint_api_v1_runs__run_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tasks
         * @description Fetch paginated list of submitted tasks.
         */
        get: operations["list_tasks_api_v1_tasks_get"];
        put?: never;
        /**
         * Submit Task
         * @description Submit a new multi-agent research task.
         */
        post: operations["create_task_api_v1_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Task Details
         * @description Get status and result payload for a specific task.
         */
        get: operations["get_task_api_v1_tasks__task_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Task
         * @description Delete a task record along with all associated logs and artifacts.
         */
        delete: operations["delete_task_api_v1_tasks__task_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Task Status
         * @description Update task lifecycle state, final result JSON, or error message.
         */
        patch: operations["update_task_api_v1_tasks__task_id__patch"];
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List runs for a task
         * @description Every run of a task.
         *
         *     Exactly one today, by the "a Task is a Run" convention — the endpoint exists in its
         *     plural form because that convention is temporary and the clients written against it
         *     should not have to change when it ends.
         */
        get: operations["list_task_runs_api_v1_tasks__task_id__runs_get"];
        put?: never;
        /**
         * Start a run
         * @description Enqueue a run for `task_id` and return where to watch it.
         *
         *     Three independent things stop this from starting the same run twice, and they cover
         *     different windows: `Idempotency-Key` catches a retried HTTP request, the `ACTIVE_STATUSES`
         *     check catches a second deliberate dispatch, and arq's job id catches a race between two
         *     API processes. The run lock in the worker is the last line, for the case where all
         *     three are somehow passed.
         */
        post: operations["create_run_api_v1_tasks__task_id__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ws/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mint a WebSocket ticket
         * @description Exchange a bearer token for a single-use, run-scoped, 60-second ticket (§9.3).
         */
        post: operations["create_ticket_api_v1_ws_tickets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BenchmarkCaseRead
         * @description One case as declared in the suite file.
         */
        BenchmarkCaseRead: {
            /** Expect */
            expect?: {
                [key: string]: unknown;
            };
            /** Id */
            id: string;
            /** Prompt */
            prompt: string;
            /**
             * Task Kind
             * @default
             */
            task_kind: string;
            /**
             * Tests
             * @description What judgement this case is testing, if it is a trap.
             * @default
             */
            tests: string;
            /**
             * Trap
             * @description Judgement cases are scored separately and never averaged in.
             * @default false
             */
            trap: boolean;
        };
        /**
         * BenchmarkKpis
         * @description The platform KPIs of AGENTS.md §13.1, over the rows returned.
         */
        BenchmarkKpis: {
            /** Cases Scored */
            cases_scored: number;
            /** Expectations Met */
            expectations_met: number;
            /**
             * First Pass Rate
             * @description Succeeded with 0 debug iterations. Target ≥ 0.40.
             */
            first_pass_rate: number;
            /**
             * Judgement Score
             * @description Trap cases passed. Target ≥ 2/3.
             */
            judgement_score: string;
            /**
             * Mean Debug Iterations
             * @description Over successful runs. Target ≤ 1.5.
             */
            mean_debug_iterations: number;
            /**
             * Replan Rate
             * @description Runs needing ≥ 1 replan. Target ≤ 0.25.
             */
            replan_rate: number;
            /**
             * Task Success Rate
             * @description SUCCEEDED / total. Target ≥ 0.70.
             */
            task_success_rate: number;
        };
        /** BenchmarkResultRead */
        BenchmarkResultRead: {
            /** Case Id */
            case_id: string;
            /** Checks */
            checks?: {
                [key: string]: unknown;
            }[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Metrics */
            metrics?: {
                [key: string]: unknown;
            };
            /** Outcome */
            outcome?: string | null;
            /** Passed */
            passed: boolean;
            /** Run Id */
            run_id?: string | null;
            /** Suite */
            suite: string;
            /** Task Id */
            task_id?: string | null;
        };
        /** BenchmarkResultsResponse */
        BenchmarkResultsResponse: {
            kpis: components["schemas"]["BenchmarkKpis"];
            /** Results */
            results: components["schemas"]["BenchmarkResultRead"][];
            /** Suite */
            suite: string;
            /** Total */
            total: number;
        };
        /**
         * BenchmarkRunAccepted
         * @description 202 — the suite is running in the background; poll `/results` for scores.
         */
        BenchmarkRunAccepted: {
            /** Cases */
            cases: string[];
            /** Message */
            message: string;
            /** Suite */
            suite: string;
            /** Version */
            version: string;
        };
        /**
         * BenchmarkRunRequest
         * @description Optional narrowing of a suite execution to specific cases.
         */
        BenchmarkRunRequest: {
            /**
             * Cases
             * @description Case ids to run. Omit to run the whole suite.
             */
            cases?: string[] | null;
        };
        /** BenchmarkSuiteListResponse */
        BenchmarkSuiteListResponse: {
            /** Suites */
            suites: components["schemas"]["BenchmarkSuiteRead"][];
            /** Total */
            total: number;
        };
        /** BenchmarkSuiteRead */
        BenchmarkSuiteRead: {
            /** Cases */
            cases?: components["schemas"]["BenchmarkCaseRead"][];
            /**
             * Description
             * @default
             */
            description: string;
            /** Name */
            name: string;
            /** Version */
            version: string;
        };
        /**
         * CorpusDocumentCreate
         * @description Payload for ingesting one document into the corpus.
         */
        CorpusDocumentCreate: {
            /**
             * Collection
             * @default rd_corpus
             * @enum {string}
             */
            collection: "rd_corpus" | "code_exemplars";
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /**
             * Source Uri
             * @description Where this came from. Defaults to a synthetic upload URI.
             */
            source_uri?: string | null;
            /** Tags */
            tags?: string[];
            /**
             * Text
             * @description Raw document text to chunk and index.
             */
            text: string;
            /** Title */
            title: string;
        };
        /** CorpusDocumentListResponse */
        CorpusDocumentListResponse: {
            /** Documents */
            documents: components["schemas"]["CorpusDocumentRead"][];
            /** Total */
            total: number;
        };
        /** CorpusDocumentRead */
        CorpusDocumentRead: {
            /** Chunk Count */
            chunk_count: number;
            /** Collection */
            collection: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Ingested At
             * Format: date-time
             */
            ingested_at: string;
            /** Metadata Json */
            metadata_json?: {
                [key: string]: unknown;
            } | null;
            /** Sha256 */
            sha256: string;
            /** Source Uri */
            source_uri: string;
            /** Title */
            title: string;
        };
        /** CorpusSearchHit */
        CorpusSearchHit: {
            /** Point Id */
            point_id: string;
            /** Score */
            score: number;
            /**
             * Section
             * @default
             */
            section: string;
            /**
             * Source Uri
             * @default
             */
            source_uri: string;
            /** Text */
            text: string;
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Trust Level
             * @default curated
             */
            trust_level: string;
        };
        /**
         * CorpusSearchRequest
         * @description Debug retrieval directly — what the Researcher would see for this query.
         */
        CorpusSearchRequest: {
            /**
             * Collection
             * @default rd_corpus
             * @enum {string}
             */
            collection: "rd_corpus" | "code_exemplars" | "run_memory";
            /** Query */
            query: string;
            /**
             * Task Kind
             * @description Filters code_exemplars/run_memory to this task kind.
             */
            task_kind?: string | null;
            /**
             * Top K
             * @default 6
             */
            top_k: number;
        };
        /** CorpusSearchResponse */
        CorpusSearchResponse: {
            /** Collection */
            collection: string;
            /** Hits */
            hits: components["schemas"]["CorpusSearchHit"][];
            /** Query */
            query: string;
        };
        /**
         * DeepHealthResponse
         * @description Deep system status response evaluating all downstream container dependencies.
         */
        DeepHealthResponse: {
            /** Services */
            services: {
                [key: string]: components["schemas"]["ServiceStatus"];
            };
            /**
             * Status
             * @example healthy
             */
            status: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthCheckResponse
         * @description Shallow system status response.
         */
        HealthCheckResponse: {
            /**
             * Environment
             * @example development
             */
            environment: string;
            /**
             * Status
             * @default ok
             * @example ok
             */
            status: string;
        };
        /**
         * RunAccepted
         * @description `202 Accepted` from `POST /tasks/{task_id}/runs` (§5.2).
         *
         *     Carries `ws_url` so the browser can open the stream without knowing how the path is
         *     assembled, and `already_running` so an idempotent replay of the same request is
         *     distinguishable from a fresh dispatch by something other than luck.
         */
        RunAccepted: {
            /**
             * Already Running
             * @default false
             */
            already_running: boolean;
            /** Job Id */
            job_id?: string | null;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Status
             * @default QUEUED
             */
            status: string;
            /**
             * Task Id
             * Format: uuid
             */
            task_id: string;
            /** Ws Url */
            ws_url: string;
        };
        /**
         * RunApproveRequest
         * @description Release a HITL gate (§9.5's `approve`).
         */
        RunApproveRequest: {
            /** Decision */
            decision: string;
            /** Gate */
            gate: string;
            /** Notes */
            notes?: string | null;
        };
        /** RunCancelRequest */
        RunCancelRequest: {
            /** Reason */
            reason?: string | null;
        };
        /**
         * RunEvent
         * @description One entry of the durable log, in the §9.2 envelope shape.
         */
        RunEvent: {
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
            /** Run Id */
            run_id: string;
            /** Seq */
            seq: number;
            /** Ts */
            ts: string;
            /** Type */
            type: string;
            /**
             * V
             * @default 1
             */
            v: number;
        };
        /**
         * RunEventsResponse
         * @description `GET /runs/{run_id}/events?after_seq=` — the same backlog the WebSocket replays.
         *
         *     Exists so a client that cannot hold a socket open (curl, a test, a notebook) reads the
         *     identical history a browser does, from the identical source. A second code path that
         *     reconstructed events from database rows would drift from the stream the moment either
         *     side changed.
         */
        RunEventsResponse: {
            /** After Seq */
            after_seq: number;
            /** Events */
            events: components["schemas"]["RunEvent"][];
            /**
             * Gap
             * @description True when `after_seq` predates retention: history the caller asked for has been trimmed.
             * @default false
             */
            gap: boolean;
            /** Last Seq */
            last_seq: number;
            /** Oldest Available */
            oldest_available?: number | null;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Total */
            total: number;
        };
        /** RunListResponse */
        RunListResponse: {
            /** Runs */
            runs: components["schemas"]["RunRead"][];
            /** Total */
            total: number;
        };
        /**
         * RunRead
         * @description Run detail — the body `GET /runs/{run_id}` returns and `run.snapshot` carries.
         */
        RunRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Current Node */
            current_node?: string | null;
            /**
             * Debug Iterations
             * @default 0
             */
            debug_iterations: number;
            /** Error */
            error?: string | null;
            /**
             * Last Seq
             * @default 0
             */
            last_seq: number;
            /**
             * Node Visits
             * @default 0
             */
            node_visits: number;
            /** Outcome */
            outcome?: string | null;
            /** Percent */
            percent?: number | null;
            /** Phase */
            phase?: string | null;
            /** Prompt */
            prompt: string;
            /**
             * Replan Count
             * @default 0
             */
            replan_count: number;
            /** Result */
            result?: {
                [key: string]: unknown;
            } | null;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            status: components["schemas"]["TaskStatus"];
            /**
             * Status Detail
             * @description The §5.3 state when it is finer than the durable column: QUEUED, AWAITING_INPUT, PARTIAL, INTERRUPTED.
             */
            status_detail?: string | null;
            /**
             * Task Id
             * Format: uuid
             */
            task_id: string;
            /** Title */
            title: string;
            /**
             * Tokens In
             * @default 0
             */
            tokens_in: number;
            /**
             * Tokens Out
             * @default 0
             */
            tokens_out: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Worker Id */
            worker_id?: string | null;
            /** Ws Url */
            ws_url: string;
        };
        /**
         * ServiceStatus
         * @description Detailed health status for an individual infrastructure service.
         */
        ServiceStatus: {
            /**
             * Message
             * @example Connected successfully
             */
            message?: string | null;
            /**
             * Required
             * @default true
             * @example true
             */
            required: boolean;
            /**
             * Status
             * @example healthy
             */
            status: string;
        };
        /**
         * StandardResponse
         * @description Generic status response payload.
         */
        StandardResponse: {
            /** Data */
            data?: {
                [key: string]: unknown;
            } | null;
            /** Message */
            message: string;
            /**
             * Success
             * @default true
             */
            success: boolean;
        };
        /**
         * TaskCreate
         * @description Payload schema for submitting a new agent workflow task.
         */
        TaskCreate: {
            /**
             * Prompt
             * @description Detailed prompt outlining instructions for the agent network.
             * @example Research MNIST architectures, write training script, and log metrics to MLflow.
             */
            prompt: string;
            /**
             * Title
             * @description Concise descriptive title for the task.
             * @example Train PyTorch MNIST Model
             */
            title: string;
        };
        /**
         * TaskListResponse
         * @description Paginated task list response.
         */
        TaskListResponse: {
            /** Tasks */
            tasks: components["schemas"]["TaskRead"][];
            /** Total */
            total: number;
        };
        /**
         * TaskRead
         * @description Response schema returning full task details.
         */
        TaskRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Prompt */
            prompt: string;
            /** Result */
            result?: {
                [key: string]: unknown;
            } | null;
            status: components["schemas"]["TaskStatus"];
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * TaskStatus
         * @description Lifecycle status states for multi-agent task execution.
         * @enum {string}
         */
        TaskStatus: "PENDING" | "RUNNING" | "COMPLETED" | "FAILED" | "CANCELLED" | "INTERRUPTED";
        /**
         * TaskUpdate
         * @description Schema for updating task status or final results.
         */
        TaskUpdate: {
            /** Error */
            error?: string | null;
            /** Result */
            result?: {
                [key: string]: unknown;
            } | null;
            status?: components["schemas"]["TaskStatus"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WsTicketRequest */
        WsTicketRequest: {
            /** Run Id */
            run_id: string;
        };
        /**
         * WsTicketResponse
         * @description A single-use, run-scoped, 60-second credential (§9.3).
         *
         *     `ws_url` is returned assembled rather than left to the client to build: the query
         *     parameter names are part of the protocol, and a client that spells `after_seq` wrong
         *     silently replays the whole backlog on every reconnect instead of failing loudly.
         */
        WsTicketResponse: {
            /** Expires In */
            expires_in: number;
            /** Run Id */
            run_id: string;
            /** Ticket */
            ticket: string;
            /** Ws Url */
            ws_url: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_benchmark_suites_api_v1_benchmarks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BenchmarkSuiteListResponse"];
                };
            };
        };
    };
    get_benchmark_results_api_v1_benchmarks__suite__results_get: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Score only the most recent run of each case, which is what the KPI targets are defined over. */
                latest_only?: boolean;
            };
            header?: never;
            path: {
                suite: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BenchmarkResultsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_benchmark_suite_api_v1_benchmarks__suite__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                suite: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["BenchmarkRunRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BenchmarkRunAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_api_v1_corpus_documents_get: {
        parameters: {
            query?: {
                collection?: string | null;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorpusDocumentListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_document_api_v1_corpus_documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorpusDocumentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorpusDocumentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_document_api_v1_corpus_documents__doc_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StandardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_corpus_api_v1_corpus_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorpusSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorpusSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthCheckResponse"];
                };
            };
        };
    };
    deep_health_check_api_v1_health_deep_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeepHealthResponse"];
                };
            };
        };
    };
    get_run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_run_api_v1_runs__run_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunApproveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StandardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_api_v1_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RunCancelRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StandardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_events_api_v1_runs__run_id__events_get: {
        parameters: {
            query?: {
                /** @description Return events with seq > this value. */
                after_seq?: number;
                limit?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunEventsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_run_endpoint_api_v1_runs__run_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StandardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tasks_api_v1_tasks_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_task_api_v1_tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_api_v1_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_task_api_v1_tasks__task_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StandardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_task_api_v1_tasks__task_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_task_runs_api_v1_tasks__task_id__runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_api_v1_tasks__task_id__runs_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_ticket_api_v1_ws_tickets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WsTicketRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WsTicketResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
