/**
 * The ONLY place the generated OpenAPI types are unpacked (docs/FRONTEND.md §4.2).
 *
 * `api.d.ts` is generated by `make fe-types` and must never be edited or imported
 * directly. Every module reads its REST types from here instead, so a backend schema
 * rename is one edit in this file rather than forty across the app — and, because the
 * names below are pulled out of `components["schemas"]`, a *removed* schema is a
 * TypeScript error here rather than an `undefined` rendered into a table cell.
 *
 * Nothing in this file is hand-written structure. If a type you want is not in
 * `components["schemas"]`, it is a view model and belongs in `types.ts` (§4.5).
 */

import type { components, operations, paths } from "./api.d";

type Schemas = components["schemas"];

// ── Runs ─────────────────────────────────────────────────────────────────────
export type RunRead = Schemas["RunRead"];
export type RunAccepted = Schemas["RunAccepted"];
export type RunListResponse = Schemas["RunListResponse"];
export type RunEventsResponse = Schemas["RunEventsResponse"];
export type RunEventRecord = Schemas["RunEvent"];
export type RunCancelRequest = Schemas["RunCancelRequest"];
export type RunApproveRequest = Schemas["RunApproveRequest"];

// ── Tasks ────────────────────────────────────────────────────────────────────
export type TaskRead = Schemas["TaskRead"];
export type TaskCreate = Schemas["TaskCreate"];
export type TaskUpdate = Schemas["TaskUpdate"];
export type TaskListResponse = Schemas["TaskListResponse"];

/**
 * The durable `tasks.status` column.
 *
 * Derived from the generated enum rather than re-listed: §5.3's finer states — `QUEUED`,
 * `AWAITING_INPUT`, `PARTIAL`, `INTERRUPTED` — are *not* in it. They arrive in
 * `RunRead.status_detail`, and `RunStatusDetail` below is the hand-written half of that
 * split, exempt under §4.5 because no backend model enumerates it.
 */
export type TaskStatus = Schemas["TaskStatus"];

// ── Corpus ───────────────────────────────────────────────────────────────────
export type CorpusDocumentRead = Schemas["CorpusDocumentRead"];
export type CorpusDocumentCreate = Schemas["CorpusDocumentCreate"];
export type CorpusDocumentListResponse = Schemas["CorpusDocumentListResponse"];
export type CorpusSearchRequest = Schemas["CorpusSearchRequest"];
export type CorpusSearchResponse = Schemas["CorpusSearchResponse"];
export type CorpusSearchHit = Schemas["CorpusSearchHit"];

// ── Benchmarks ───────────────────────────────────────────────────────────────
export type BenchmarkSuiteRead = Schemas["BenchmarkSuiteRead"];
export type BenchmarkSuiteListResponse = Schemas["BenchmarkSuiteListResponse"];
export type BenchmarkCaseRead = Schemas["BenchmarkCaseRead"];
export type BenchmarkResultRead = Schemas["BenchmarkResultRead"];
export type BenchmarkResultsResponse = Schemas["BenchmarkResultsResponse"];
export type BenchmarkRunRequest = Schemas["BenchmarkRunRequest"];
export type BenchmarkRunAccepted = Schemas["BenchmarkRunAccepted"];
export type BenchmarkKpis = Schemas["BenchmarkKpis"];

// ── Health, protocol, envelopes ───────────────────────────────────────────────
export type HealthCheckResponse = Schemas["HealthCheckResponse"];
export type DeepHealthResponse = Schemas["DeepHealthResponse"];
export type ServiceStatus = Schemas["ServiceStatus"];
export type StandardResponse = Schemas["StandardResponse"];
export type WsTicketRequest = Schemas["WsTicketRequest"];
export type WsTicketResponse = Schemas["WsTicketResponse"];

// ── Operation helpers ────────────────────────────────────────────────────────

/** Every path the generated document knows about. Used to key the fetch wrapper. */
export type ApiPath = keyof paths;

/** The success body of one operation, for the fetch wrapper's return type. */
export type ResponseOf<O extends keyof operations> =
  operations[O] extends { responses: infer R }
    ? R extends { 200: { content: { "application/json": infer B } } }
      ? B
      : R extends { 202: { content: { "application/json": infer B } } }
        ? B
        : never
    : never;

/** The JSON request body of one operation, for the fetch wrapper's argument type. */
export type BodyOf<O extends keyof operations> =
  operations[O] extends { requestBody?: { content: { "application/json": infer B } } }
    ? B
    : never;
