/**
 * Hand-written view models for the REST bodies this app reads.
 *
 * ARCHITECTURE.md §18.5 wants these generated by `openapi-typescript` against a live
 * `/api/v1/openapi.json` (`make fe-types` writes `src/lib/api.d.ts`). That needs the API
 * running, so it cannot be the only source: these are the narrow subset the UI actually
 * touches, kept small on purpose so the generated file stays the authority on everything
 * else. The WebSocket half of the contract *is* generated, by `make gen-event-types`, and
 * lives in `events.generated.ts`.
 */

/** The durable `tasks.status` column. §5.3's finer states arrive in `status_detail`. */
export type RunStatus =
  | "PENDING"
  | "RUNNING"
  | "COMPLETED"
  | "FAILED"
  | "CANCELLED"
  | "INTERRUPTED";

/** The coarse progress signal every node sets on entry (`engine/state.py` RunPhase). */
export type RunPhase =
  | "INIT"
  | "PLANNING"
  | "RESEARCH"
  | "IMPLEMENT"
  | "EXECUTE"
  | "DEBUG"
  | "TRACK"
  | "EVALUATE"
  | "REPORT"
  | "COMPLETE";

/** `GET /runs/{run_id}`, and the body `run.snapshot` carries. */
export interface RunDetail {
  run_id: string;
  task_id: string;
  title: string;
  prompt: string;
  status: RunStatus;
  status_detail: string | null;
  phase: RunPhase | null;
  current_node: string | null;
  percent: number | null;
  outcome: string | null;
  last_seq: number;
  worker_id: string | null;
  tokens_in: number;
  tokens_out: number;
  node_visits: number;
  debug_iterations: number;
  replan_count: number;
  error: string | null;
  result: Record<string, unknown> | null;
  created_at: string;
  updated_at: string;
  ws_url: string;
}

export interface TaskSummary {
  id: string;
  title: string;
  prompt: string;
  status: RunStatus;
  error: string | null;
  created_at: string;
  updated_at: string;
}

export interface TaskListResponse {
  total: number;
  tasks: TaskSummary[];
}

export interface RunAccepted {
  run_id: string;
  task_id: string;
  status: string;
  job_id: string | null;
  ws_url: string;
  already_running: boolean;
}

export interface WsTicket {
  ticket: string;
  run_id: string;
  expires_in: number;
  ws_url: string;
}

/** One line of sandbox output, as the console pane holds it. */
export interface ConsoleLine {
  id: number;
  stream: "stdout" | "stderr" | "token";
  text: string;
  ts: string;
  node?: string;
  executionId?: string;
}

/** One node's entry in the timeline pane, folded from `node.*` events. */
export interface TimelineEntry {
  node: string;
  seq: number;
  status: "running" | "succeeded" | "failed" | "degraded";
  startedAt: string;
  durationMs?: number;
  tokensOut?: number;
  summary?: string;
  error?: string;
}

/** A criterion row under the timeline, from `plan.created` and `evaluation.completed`. */
export interface CriterionRow {
  id: string;
  metric: string;
  comparator: string;
  threshold: number;
  required: boolean;
  observed?: number | null;
  passed?: boolean;
}

/** An entry in the artifact pane, from `artifact.created`. */
export interface ArtifactRow {
  artifact_id?: string;
  name: string;
  type: string;
  size_bytes?: number;
  sha256?: string;
  download_url?: string;
}

/** A point on a metric curve, from `metric.logged`. */
export interface MetricPoint {
  key: string;
  value: number;
  step: number;
}
